version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
      - DEBUG=${DEBUG:-false}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./uploads:/tmp/document-uploads
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  worker:
    build: .
    command: celery -A app.workers worker --loglevel=info
    environment:
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./uploads:/tmp/document-uploads
    depends_on:
      - redis
    restart: unless-stopped

volumes:
  redis_data:
  uploads: